# Generated by Django 5.0.6 on 2024-08-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Photo URL'),
        ),
    ]
